### ISSUE TITLE
pytube 3 keyError: 'assets'

### ISSUE THREAD

**Issue by okanyesil** [get-pytube/pytube3#108]
I am trying to download video from youtube. I installed pytube pip install pytube3. when I am trying to download a video it gives me this error 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\OKAN\AppData\Roaming\Python\Python38\site-packages\pytube\__main__.py", line 91, in __init__
    self.prefetch()
  File "C:\Users\OKAN\AppData\Roaming\Python\Python38\site-packages\pytube\__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "C:\Users\OKAN\AppData\Roaming\Python\Python38\site-packages\pytube\extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
KeyError: 'assets'

**Comment by AssesBesses** [comment]
here is the solution
https://github.com/nficano/pytube/issues/777

**Comment by okanyesil** [comment]
it didnt help me

**Comment by AssesBesses** [comment]
What error are you getting?

**Comment by okanyesil** [comment]
Same error

**Comment by AssesBesses** [comment]
Download the original pytube from github https://github.com/nficano/pytube
Don't use pip, download directly from github.
pytube works fine with up to python 3.7

**Comment by bigbear22941** [comment]
Copy code from codebas still not work for me, too...

**Comment by AssesBesses** [comment]
what version of python are you using?
