### ISSUE TITLE
How many request from pytube??  HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by Vallofe** [get-pytube/pytube3#110]
[ 02 - November - 2020 | 19:37:28 ] pplaylist ERROR: Traceback (most recent call last):
  File "/root/.selfbot/liff.py", line 996, in pplaylist
    playlist = Playlist(sett['playlist'][query])
  File "/usr/local/lib/python3.6/dist-packages/pytube/contrib/playlist.py", line 41, in __init__
    self.html = request.get(self.playlist_url)
  File "/usr/local/lib/python3.6/dist-packages/pytube/request.py", line 43, in get
    return _execute_request(url, headers=extra_headers).read().decode("utf-8")
  File "/usr/local/lib/python3.6/dist-packages/pytube/request.py", line 27, in _execute_request
    return urlopen(request)  # nosec
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

**Comment by hamidb80** [comment]
Few days ago Youtube has updated and some of the Youtube-downloaders are not working anymore
