### ISSUE TITLE
RegexMatchError

### ISSUE THREAD

**Issue by gdejongh** [get-pytube/pytube3#67]
I have the code copied word for word from the documentation:

>>>from pytube import YouTube

>>>yt = YouTube('http://youtube.com/watch?v=9bZkp7q19f0')

returns this error message:

Traceback (most recent call last):
  File "tester.py", line 3, in <module>
    yt = YouTube('http://youtube.com/watch?v=9bZkp7q19f0')
  File "/Users/gabedejongh/Library/Python/3.7/lib/python/site-packages/pytube-9.6.0-py3.7.egg/pytube/__main__.py", line 92, in __init__
  File "/Users/gabedejongh/Library/Python/3.7/lib/python/site-packages/pytube-9.6.0-py3.7.egg/pytube/__main__.py", line 101, in prefetch_init
  File "/Users/gabedejongh/Library/Python/3.7/lib/python/site-packages/pytube-9.6.0-py3.7.egg/pytube/__main__.py", line 148, in init
  File "/Users/gabedejongh/Library/Python/3.7/lib/python/site-packages/pytube-9.6.0-py3.7.egg/pytube/mixins.py", line 53, in apply_signature
  File "/Users/gabedejongh/Library/Python/3.7/lib/python/site-packages/pytube-9.6.0-py3.7.egg/pytube/cipher.py", line 259, in get_signature
  File "/Users/gabedejongh/Library/Python/3.7/lib/python/site-packages/pytube-9.6.0-py3.7.egg/pytube/cipher.py", line 78, in get_transform_plan
  File "/Users/gabedejongh/Library/Python/3.7/lib/python/site-packages/pytube-9.6.0-py3.7.egg/pytube/cipher.py", line 54, in get_initial_function_name
  File "/Users/gabedejongh/Library/Python/3.7/lib/python/site-packages/pytube-9.6.0-py3.7.egg/pytube/helpers.py", line 41, in regex_search
pytube.exceptions.RegexMatchError: regex pattern (\b[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*encodeURIComponent\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\() had zero matches

**Comment by hbmartin** [comment]
Look like a pytube issue, not pytube3. Please reopen if I'm mistaken.
