### ISSUE TITLE
New parsing issue.

### ISSUE THREAD

**Issue by guruofnibiru** [get-pytube/pytube3#77]
Traceback (most recent call last):
  File "yt-download.py", line 21, in youtube_download
    yt = YouTube(yt_url)
  File "/Users/ray/Documents/Code/youtube/env/lib/python3.8/site-packages/pytube/__main__.py", line 77, in __init__
    self.video_id = extract.video_id(url)
  File "/Users/ray/Documents/Code/youtube/env/lib/python3.8/site-packages/pytube/extract.py", line 80, in video_id
    return regex_search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", url, group=1)
  File "/Users/ray/Documents/Code/youtube/env/lib/python3.8/site-packages/pytube/helpers.py", line 34, in regex_search
    raise RegexMatchError(caller="regex_search", pattern=pattern)
pytube.exceptions.RegexMatchError: regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).*

**Comment by tooxo** [comment]
Can you provide the url you used while getting this error?
