### ISSUE TITLE
KeyError: 'cipher'

### ISSUE THREAD

**Issue by Jabyer** [get-pytube/pytube3#82]
in video: https://www.youtube.com/watch?v=sh9SBIMGLAI&t=2827s

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Thonny\lib\site-packages\pytube\extract.py", line 297, in apply_descrambler
    for format_item in formats
  File "C:\Users\user\AppData\Local\Programs\Thonny\lib\site-packages\pytube\extract.py", line 297, in <listcomp>
    for format_item in formats
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MEGA\Programación\Python\Descargar videos de Youtube.py", line 19, in <module>
    YouTube(url).streams.first().download()
  File "C:\Users\user\AppData\Local\Programs\Thonny\lib\site-packages\pytube\__main__.py", line 92, in __init__
    self.descramble()
  File "C:\Users\user\AppData\Local\Programs\Thonny\lib\site-packages\pytube\__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "C:\Users\user\AppData\Local\Programs\Thonny\lib\site-packages\pytube\extract.py", line 301, in apply_descrambler
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
  File "C:\Users\user\AppData\Local\Programs\Thonny\lib\site-packages\pytube\extract.py", line 301, in <listcomp>
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
KeyError: 'cipher'

**Comment by Boidushya** [comment]
Refer to PR #80 , it is a potential fix to the issue
