### ISSUE TITLE
KeyError: 'url'

### ISSUE THREAD

**Issue by Kiriru777** [get-pytube/pytube3#92]
MacOS 10.6.8
Python 3.6.1
Pytube3-9.6.4

Error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytube/extract.py", line 297, in apply_descrambler for format_item in formats
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytube/extract.py", line 297, in <listcomp> for format_item in formats
KeyError: 'url'

while fetching:
https://www.youtube.com/watch?v=1CVlBSgj0bk

What I did to install pytube3:
aaa:~ bbb$: python3.6 -m pip install pytube3

Any ideas would be greatly appreciated!
Regards

**Comment by Kiriru777** [comment]
Update: I followed this advice to update extract.py #80:
https://github.com/get-pytube/pytube3/pull/80/commits/5ac96de69f025b09abf2a6a24a4103c78b7e4c81

But fetched video title is always 'You Tube'

**Comment by jamadagni** [comment]
Curious. For some URLs the error doesn't come: https://www.youtube.com/watch?v=Mr1beO3B120
